[project]
name = "frappe_preview_image"
version = "0.0.1"
description = "Frappe Preview Image"
authors = [
  { name = "Günther Eder", email = "guenther.eder@indigitalform.com" }
]
dependencies = [
]

[build-system]
requires = [
]
build-backend = "setuptools.build_meta"